var idCrop = charIDToTypeID( "Crop" );
    var desc644 = new ActionDescriptor();
    var idT = charIDToTypeID( "T   " );
        var desc645 = new ActionDescriptor();
        var idTop = charIDToTypeID( "Top " );
        var idPxl = charIDToTypeID( "#Pxl" );
        desc645.putUnitDouble( idTop, idPxl, 396.000000 );
        var idLeft = charIDToTypeID( "Left" );
        var idPxl = charIDToTypeID( "#Pxl" );
        desc645.putUnitDouble( idLeft, idPxl, 0.000000 );
        var idBtom = charIDToTypeID( "Btom" );
        var idPxl = charIDToTypeID( "#Pxl" );
        desc645.putUnitDouble( idBtom, idPxl, 1962.000000 );
        var idRght = charIDToTypeID( "Rght" );
        var idPxl = charIDToTypeID( "#Pxl" );
        desc645.putUnitDouble( idRght, idPxl, 1566.000000 );
    var idRctn = charIDToTypeID( "Rctn" );
    desc644.putObject( idT, idRctn, desc645 );
    var idAngl = charIDToTypeID( "Angl" );
    var idAng = charIDToTypeID( "#Ang" );
    desc644.putUnitDouble( idAngl, idAng, 0.000000 );
    var idDlt = charIDToTypeID( "Dlt " );
    desc644.putBoolean( idDlt, false );
    var idautoFill = stringIDToTypeID( "autoFill" );
    desc644.putBoolean( idautoFill, true );
    // var idcropAspectRatioModeKey = stringIDToTypeID( "cropAspectRatioModeKey" );
    // var idcropAspectRatioModeClass = stringIDToTypeID( "cropAspectRatioModeClass" );
    // var idtargetSize = stringIDToTypeID( "targetSize" );
    // desc644.putEnumerated( idcropAspectRatioModeKey, idcropAspectRatioModeClass, idtargetSize );
    var idWdth = charIDToTypeID( "Wdth" );
    var idPxl = charIDToTypeID( "#Pxl" );
    desc644.putUnitDouble( idWdth, idPxl, 2358.000000 );
    // var idHght = charIDToTypeID( "Hght" );
    // var idPxl = charIDToTypeID( "#Pxl" );
    // desc644.putUnitDouble( idHght, idPxl, 2358.000000 );
    // var idRslt = charIDToTypeID( "Rslt" );
    // var idRsl = charIDToTypeID( "#Rsl" );
    // desc644.putUnitDouble( idRslt, idRsl, 96.000000 );
executeAction( idCrop, desc644, DialogModes.NO );